<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.2 (Python 3.10.1 on win32)" generated="20211210 00:43:23.300" rpa="false" schemaversion="2">
<suite id="s1" name="Hurb" source="D:\CertifieldTechDeveloper\CTD_Codigos\CodigosBII\Testing\aula22\hurb.robot">
<test id="s1-t1" name="Processo de reserva de pacote de viagens">
<kw name="Abrir o site Hurb" library="Hurb" type="SETUP">
<kw name="Open Browser">
<arg>${SITE}</arg>
<arg>${NAVEGADOR}</arg>
<msg timestamp="20211210 00:43:23.349" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20211210 00:43:23.349" endtime="20211210 00:43:23.349"/>
</kw>
<status status="FAIL" starttime="20211210 00:43:23.346" endtime="20211210 00:43:23.350"/>
</kw>
<status status="FAIL" starttime="20211210 00:43:23.345" endtime="20211210 00:43:23.350">Setup failed:
No keyword with name 'Open Browser' found.</status>
</test>
<status status="FAIL" starttime="20211210 00:43:23.302" endtime="20211210 00:43:23.352"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Hurb">Hurb</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20211210 00:43:23.332" level="ERROR">Error in file 'D:\CertifieldTechDeveloper\CTD_Codigos\CodigosBII\Testing\aula22\hurb.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\wagne\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  C:\Users\wagne\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\wagne\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\wagne\AppData\Local\Programs\Python\Python310\lib
  C:\Users\wagne\AppData\Local\Programs\Python\Python310
  C:\Users\wagne\AppData\Local\Programs\Python\Python310\lib\site-packages</msg>
</errors>
</robot>
